pipeline {
    agent any
    environment {
        DOCKER_PATH = "C:\\Program Files\\Docker\\cli-plugins"
        PATH = "${DOCKER_PATH}:${PATH}"
        NODEJS_PATH = "C:\\Program Files (x86)\\nodejs"
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Build and Rename Docker Image') {
            steps {
                script {
                    // Use the default Dockerfile name and build context
                    bat 'docker build -t cagnotte-v2_%BUILD_ID% .'

                    // Renaming the Docker image
                    bat "docker tag cagnotte-v2_%BUILD_ID% faika/cagnotte-v2_%BUILD_ID%"
                }
            }
        }

        stage('Build and Run Docker Container') {
            steps {
                script {
                    // Running the Docker container
                    bat "docker run -d --name dashboard_admin faika/cagnotte-v2_${BUILD_ID}"
                }
            }
        }
    }
}
